# coding: utf-8

"""
    Veeva Vault API v25.1

    The latest GA version of the Vault REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from veeva.models.merge_request import MergeRequest

class TestMergeRequest(unittest.TestCase):
    """MergeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MergeRequest:
        """Test MergeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MergeRequest`
        """
        model = MergeRequest()
        if include_optional:
            return MergeRequest(
                duplicate_record_id = '',
                main_record_id = ''
            )
        else:
            return MergeRequest(
        )
        """

    def testMergeRequest(self):
        """Test MergeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
