# coding: utf-8

# flake8: noqa

"""
    Veeva Vault API v25.1

    The latest GA version of the Vault REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "VeevaApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "VeevaException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "MergeRequest",
    "VaultClient",
]

# import apis into sdk package
from veeva.api.veeva_api import VeevaApi

# import ApiClient
from veeva.api_response import ApiResponse
from veeva.api_client import ApiClient
from veeva.configuration import Configuration
from veeva.exceptions import VeevaException
from veeva.exceptions import ApiTypeError
from veeva.exceptions import ApiValueError
from veeva.exceptions import ApiKeyError
from veeva.exceptions import ApiAttributeError
from veeva.exceptions import ApiException
from veeva.client import VaultClient

# import models into sdk package
from veeva.models.merge_request import MergeRequest
