# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - "pip install poetry"
  - "poetry install"
# command to run tests
script: poetry run pytest --cov=veeva
